---
- name: PRINT rax server list
  hosts: localhost

  tasks:

    - name: PRINT rax server details
      local_action:
        module: rax_facts
        credentials: /root/.rackspace_cloud_credentials
        name: "{{ item }}"
        region: ORD
      with_items:
        - stack-ansible-01
        - stack-ansible-02
      register: rax

    - debug:
        var: rax
...
