---
- name: Create rax server
  hosts: localhost

  tasks:

    - name: Provision new rax server
      local_action:
        module: rax
        credentials: /root/.rackspace_cloud_credentials
        key_name: "emlee-ord"
        state: present
        name: "stack-ansible-made"
        region: "ORD"
        flavor: "2"
        image: "398c5f65-23e2-44da-97d8-d28ff5ec583b"
        wait: yes
        wait_timeout: 600
      register: rax

    - debug:
        var: rax
...
